### ISSUE TITLE
Code style/formatting

### ISSUE THREAD

**Issue by aokellermann** [aokellermann/securedrop#7]
### Description
To maintain code formatting, we should have a formatter. This issue has 3 steps:
- [x] Pick a formatter (perhaps [yapf](https://github.com/google/yapf)) and comment on this issue why you picked it, until we all agree to use it.
- [x] Write a bash script (`/scripts/format.sh`) to do two things:
  - [x] Format the code. The script should do this when run with no arguments.
  - [x] Check the code, and return a non-zero exit code if any format errors exist (this is used for CI). The script should be run with one argument : `check`.
- [x] Create a [CI step](https://github.com/aokellermann/securedrop/blob/master/.circleci/config.yml) to check the code for formatting errors.

**Comment by jjjoycing123** [comment]
Yapf seems pretty straight forward and looks likea good choice to me

**Comment by jjjoycing123** [comment]
added the following lines to the config file:
 -run:
          name: Formatting
          command: ./scripts/format.sh
